#!/bin/bash

prog="uma"
logfile="/var/log/uma.log"
running=$(pidof "$prog" | wc -w)

echo "$(date): Stopping UMA service" >> "$logfile"

# stop if running
if [ "$running" -ge 1 ]; then
  echo "$(date): UMA is running (PID: $(pidof "$prog")), stopping..." >> "$logfile"
  TIMER=0
  while killall "$prog" 2>/dev/null; do
    sleep 1
    TIMER=$((TIMER + 1))
    if [ $TIMER -ge 30 ]; then
      echo "$(date): Force killing UMA after 30 seconds" >> "$logfile"
      killall -9 "$prog"
      sleep 1
      break
    fi
  done
  echo "$(date): UMA stopped successfully" >> "$logfile"
else
  echo "$(date): UMA was not running" >> "$logfile"
fi
