#!/bin/bash
# read our configuration
source /boot/config/plugins/omniraid/omniraid.cfg

prog="/usr/local/emhttp/plugins/omniraid/omniraid"

# stop it if it's running
killall omniraid >/dev/null 2>&1

# run the app
[[ $UPS = "enable" ]] && SHOWUPS="--show-ups" || SHOWUPS=""
nohup sudo -H bash -c "$prog $SHOWUPS" >/dev/null 2>&1 &
